# Generated by Django 5.1 on 2025-11-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('housewife', 'Housewife'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='housewife', max_length=20),
        ),
    ]
