# Generated by Django 5.2.10 on 2026-02-01 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_application_created_at_application_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
